#include "mgard_nuni_2d_cuda_common.h"
#include "mgard_nuni_2d_cuda_gen.h"

#include "mgard_nuni_2d_cuda_pi_Ql_first.h"
#include "mgard_nuni_2d_cuda_restriction_first.h"
#include "mgard_nuni_2d_cuda_prolongate_last.h"
#include "mgard_nuni_2d_cuda_copy_level.h"
#include "mgard_nuni_2d_cuda_mass_matrix_multiply.h"
#include "mgard_nuni_2d_cuda_subtract_level.h"

#include "mgard_nuni_2d_cuda_pi_Ql.h"
#include "mgard_nuni_2d_cuda_mass_mult_l.h"
#include "mgard_nuni_2d_cuda_restriction_l.h"
#include "mgard_nuni_2d_cuda_solve_tridiag_M_l.h"
#include "mgard_nuni_2d_cuda_prolongate_l.h"
#include "mgard_nuni_2d_cuda_copy_level_l.h"
#include "mgard_nuni_2d_cuda_assign_num_level_l.h"
#include "mgard_nuni_2d_cuda_add_level_l.h"
#include "mgard_nuni_2d_cuda_subtract_level_l.h"
