find_package(zstd QUIET)
if (zstd_FOUND)
    message(STATUS "Found ZSTD (CMAKE): ${zstd_DIR}")
    set(ZSTD_FOUND 1)
    set(ZSTD_FOUND_BY_CMAKE 1)
else()
    pkg_search_module(ZSTD IMPORTED_TARGET GLOBAL libzstd)
    message(STATUS "Found ZSTD (PkgConfig): ${ZSTD_LINK_LIBRARIES}")
    set(ZSTD_FOUND 1)
    set(ZSTD_FOUND_BY_PKGCONFIG 1)
endif()

if(NOT ZSTD_FOUND) 
    if(ZSTD_FIND_REQUIRED)
        message(FATAL_ERROR "ZSTD not found.")
    else()
        message(STATUS "ZSTD not found.")
    endif()
endif()